name: Deploy Application

on:
  push:
    branches:
    
jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker Buildx to enable building and pushing multi-platform images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Login to DockerHub (or any other registry you're using)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/frontend:v1

    # Build and push backend Docker image
    - name: Build and push backend Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/backend:v1

    # Pull the image from the docker-hub
    - name: Image Pulling from Docker-Hub
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:v1
        docker pull ${{ secrets.DOCKER_USERNAME }}/backend:v1
        docker pull mongo:latest
    # Creating the docker volume
    - name: Creating docker volume
      run: docker volume create mongo-db 

    # Creating the docker network
    - name: creating the docker network through command only 
      run: docker network create network-backend

    # Deploy the application using Docker Compose or Docker commands
    - name: Deploying application on docker normally.
      run: |
        docker run -itd --name mongo-db --network network-backend -e MONGO_INITDB_ROOT_USERNAME=mongoUser -e MONGO_INITDB_ROOT_PASSWORD=mongoPassword -v mongo-db/data/db -p 27017:27017 mongo:latest
        docker run -itd --name web-app --network network-backend -p 3000:3000 vikash1997/frontend:v1 
        docker run -itd --name backend-app --network network-backend -p 3001:3001 vikash1997/backend:v1
